spring.application.name=mathiasruck-wallet
server.port=3003
# MySQL Configuration
spring.jpa.hibernate.ddl-auto=update
# Kafka Configuration
spring.kafka.bootstrap-servers=${KAFKA_HOST:localhost}:9092
#logging.level.org.springframework.boot.autoconfigure=DEBUG
