server:
  port: 3003
spring:
  application:
    name: mathiasruck-wallet
  kafka:
    bootstrap-servers: ${KAFKA_HOST:localhost}:${KAFKA_PORT:29092}
    consumer:
      group-id: ${KAFKA_GROUP_ID:wallet}
      auto-offset-reset: latest
test:
  topic: embedded-test-topic