### Create Client 1

POST http://localhost:8080/clients HTTP/1.1
Content-Type: application/json

{
  "name": "John Doe",
  "email": "j@j.com"
}

### Create Client 2
POST http://localhost:8080/clients HTTP/1.1
Content-Type: application/json

{
  "name": "Jane Doe",
  "email": "jane@j.com"
}

### Create Account for client 1
POST http://localhost:8080/accounts HTTP/1.1
Content-Type: application/json

{
  "client_id": "d1c64456-2454-4639-8d19-e25a6134bca1"
}

### Create Account for client 2
POST http://localhost:8080/accounts HTTP/1.1
Content-Type: application/json

{
  "client_id": "e9e05654-668d-465e-b0bd-319293461187"
}

### Create Transaction 1
POST http://localhost:8080/transactions HTTP/1.1
Content-Type: application/json

{
  "account_id_from": "3f19de80-a22c-48a6-8c76-69a7cb792aff",
  "account_id_to": "2311e1f8-0af7-4d7d-9c59-7db23af80d96",
  "amount": 5
}

### Get balance for Account 1
GET http://localhost:3003/balances/3f19de80-a22c-48a6-8c76-69a7cb792aff HTTP/1.1

### Get balance for Account 2
GET http://localhost:3003/balances/2311e1f8-0af7-4d7d-9c59-7db23af80d96 HTTP/1.1